// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: do/taxexemption/v1/query.proto

package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type QueryTaxableRequest struct {
	FromAddress string `protobuf:"bytes,1,opt,name=from_address,json=fromAddress,proto3" json:"from_address,omitempty"`
	ToAddress   string `protobuf:"bytes,2,opt,name=to_address,json=toAddress,proto3" json:"to_address,omitempty"`
}

func (m *QueryTaxableRequest) Reset()         { *m = QueryTaxableRequest{} }
func (m *QueryTaxableRequest) String() string { return proto.CompactTextString(m) }
func (*QueryTaxableRequest) ProtoMessage()    {}
func (*QueryTaxableRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c1e3fbb09d7c843, []int{0}
}
func (m *QueryTaxableRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryTaxableRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryTaxableRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryTaxableRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryTaxableRequest.Merge(m, src)
}
func (m *QueryTaxableRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryTaxableRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryTaxableRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryTaxableRequest proto.InternalMessageInfo

func (m *QueryTaxableRequest) GetFromAddress() string {
	if m != nil {
		return m.FromAddress
	}
	return ""
}

func (m *QueryTaxableRequest) GetToAddress() string {
	if m != nil {
		return m.ToAddress
	}
	return ""
}

type QueryTaxableResponse struct {
	Taxable bool `protobuf:"varint,1,opt,name=taxable,proto3" json:"taxable,omitempty"`
}

func (m *QueryTaxableResponse) Reset()         { *m = QueryTaxableResponse{} }
func (m *QueryTaxableResponse) String() string { return proto.CompactTextString(m) }
func (*QueryTaxableResponse) ProtoMessage()    {}
func (*QueryTaxableResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c1e3fbb09d7c843, []int{1}
}
func (m *QueryTaxableResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryTaxableResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryTaxableResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryTaxableResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryTaxableResponse.Merge(m, src)
}
func (m *QueryTaxableResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryTaxableResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryTaxableResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryTaxableResponse proto.InternalMessageInfo

func (m *QueryTaxableResponse) GetTaxable() bool {
	if m != nil {
		return m.Taxable
	}
	return false
}

type QueryTaxExemptionZonesRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryTaxExemptionZonesRequest) Reset()         { *m = QueryTaxExemptionZonesRequest{} }
func (m *QueryTaxExemptionZonesRequest) String() string { return proto.CompactTextString(m) }
func (*QueryTaxExemptionZonesRequest) ProtoMessage()    {}
func (*QueryTaxExemptionZonesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c1e3fbb09d7c843, []int{2}
}
func (m *QueryTaxExemptionZonesRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryTaxExemptionZonesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryTaxExemptionZonesRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryTaxExemptionZonesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryTaxExemptionZonesRequest.Merge(m, src)
}
func (m *QueryTaxExemptionZonesRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryTaxExemptionZonesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryTaxExemptionZonesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryTaxExemptionZonesRequest proto.InternalMessageInfo

func (m *QueryTaxExemptionZonesRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryTaxExemptionZonesResponse struct {
	Zones      []*Zone             `protobuf:"bytes,1,rep,name=zones,proto3" json:"zones,omitempty"`
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryTaxExemptionZonesResponse) Reset()         { *m = QueryTaxExemptionZonesResponse{} }
func (m *QueryTaxExemptionZonesResponse) String() string { return proto.CompactTextString(m) }
func (*QueryTaxExemptionZonesResponse) ProtoMessage()    {}
func (*QueryTaxExemptionZonesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c1e3fbb09d7c843, []int{3}
}
func (m *QueryTaxExemptionZonesResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryTaxExemptionZonesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryTaxExemptionZonesResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryTaxExemptionZonesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryTaxExemptionZonesResponse.Merge(m, src)
}
func (m *QueryTaxExemptionZonesResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryTaxExemptionZonesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryTaxExemptionZonesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryTaxExemptionZonesResponse proto.InternalMessageInfo

func (m *QueryTaxExemptionZonesResponse) GetZones() []*Zone {
	if m != nil {
		return m.Zones
	}
	return nil
}

func (m *QueryTaxExemptionZonesResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryTaxExemptionAddressRequest struct {
	ZoneName   string             `protobuf:"bytes,1,opt,name=zone_name,json=zoneName,proto3" json:"zone_name,omitempty"`
	Pagination *query.PageRequest `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryTaxExemptionAddressRequest) Reset()         { *m = QueryTaxExemptionAddressRequest{} }
func (m *QueryTaxExemptionAddressRequest) String() string { return proto.CompactTextString(m) }
func (*QueryTaxExemptionAddressRequest) ProtoMessage()    {}
func (*QueryTaxExemptionAddressRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c1e3fbb09d7c843, []int{4}
}
func (m *QueryTaxExemptionAddressRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryTaxExemptionAddressRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryTaxExemptionAddressRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryTaxExemptionAddressRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryTaxExemptionAddressRequest.Merge(m, src)
}
func (m *QueryTaxExemptionAddressRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryTaxExemptionAddressRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryTaxExemptionAddressRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryTaxExemptionAddressRequest proto.InternalMessageInfo

func (m *QueryTaxExemptionAddressRequest) GetZoneName() string {
	if m != nil {
		return m.ZoneName
	}
	return ""
}

func (m *QueryTaxExemptionAddressRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryTaxExemptionAddressResponse struct {
	Addresses  []string            `protobuf:"bytes,1,rep,name=addresses,proto3" json:"addresses,omitempty"`
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryTaxExemptionAddressResponse) Reset()         { *m = QueryTaxExemptionAddressResponse{} }
func (m *QueryTaxExemptionAddressResponse) String() string { return proto.CompactTextString(m) }
func (*QueryTaxExemptionAddressResponse) ProtoMessage()    {}
func (*QueryTaxExemptionAddressResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c1e3fbb09d7c843, []int{5}
}
func (m *QueryTaxExemptionAddressResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryTaxExemptionAddressResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryTaxExemptionAddressResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryTaxExemptionAddressResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryTaxExemptionAddressResponse.Merge(m, src)
}
func (m *QueryTaxExemptionAddressResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryTaxExemptionAddressResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryTaxExemptionAddressResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryTaxExemptionAddressResponse proto.InternalMessageInfo

func (m *QueryTaxExemptionAddressResponse) GetAddresses() []string {
	if m != nil {
		return m.Addresses
	}
	return nil
}

func (m *QueryTaxExemptionAddressResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryTaxableRequest)(nil), "do.taxexemption.v1.QueryTaxableRequest")
	proto.RegisterType((*QueryTaxableResponse)(nil), "do.taxexemption.v1.QueryTaxableResponse")
	proto.RegisterType((*QueryTaxExemptionZonesRequest)(nil), "do.taxexemption.v1.QueryTaxExemptionZonesRequest")
	proto.RegisterType((*QueryTaxExemptionZonesResponse)(nil), "do.taxexemption.v1.QueryTaxExemptionZonesResponse")
	proto.RegisterType((*QueryTaxExemptionAddressRequest)(nil), "do.taxexemption.v1.QueryTaxExemptionAddressRequest")
	proto.RegisterType((*QueryTaxExemptionAddressResponse)(nil), "do.taxexemption.v1.QueryTaxExemptionAddressResponse")
}

func init() { proto.RegisterFile("do/taxexemption/v1/query.proto", fileDescriptor_8c1e3fbb09d7c843) }

var fileDescriptor_8c1e3fbb09d7c843 = []byte{
	// 567 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x54, 0xcf, 0x6b, 0x13, 0x41,
	0x14, 0xee, 0x54, 0x6b, 0x9b, 0x17, 0x4f, 0xa3, 0x62, 0x4c, 0xdb, 0x35, 0x0d, 0x68, 0xa3, 0xe2,
	0x8c, 0x9b, 0x16, 0x44, 0x10, 0x44, 0xf1, 0xc7, 0x45, 0x44, 0x17, 0x51, 0xe8, 0xa5, 0x4c, 0xb2,
	0xe3, 0x76, 0xa1, 0xbb, 0xb3, 0xcd, 0x4c, 0x42, 0x6a, 0xc8, 0x45, 0x50, 0xf0, 0x26, 0x78, 0xf2,
	0xe0, 0xc1, 0xbf, 0xc2, 0x7f, 0xc1, 0x63, 0xc1, 0x8b, 0x47, 0x49, 0xfc, 0x43, 0x64, 0x67, 0x66,
	0xf3, 0x83, 0x6c, 0xad, 0x85, 0x9e, 0x42, 0xde, 0x7c, 0x6f, 0xbe, 0xef, 0x7d, 0xef, 0x9b, 0x05,
	0xc7, 0x17, 0x54, 0xb1, 0x2e, 0xef, 0xf2, 0x28, 0x51, 0xa1, 0x88, 0x69, 0xc7, 0xa5, 0x7b, 0x6d,
	0xde, 0xda, 0x27, 0x49, 0x4b, 0x28, 0x81, 0xb1, 0x2f, 0xc8, 0xe4, 0x39, 0xe9, 0xb8, 0xe5, 0x95,
	0x40, 0x88, 0x60, 0x97, 0x53, 0x96, 0x84, 0x94, 0xc5, 0xb1, 0x50, 0x2c, 0x3d, 0x91, 0xa6, 0xa3,
	0x7c, 0xbd, 0x29, 0x64, 0x24, 0x24, 0x6d, 0x30, 0xc9, 0xcd, 0x55, 0xb4, 0xe3, 0x36, 0xb8, 0x62,
	0x2e, 0x4d, 0x58, 0x10, 0xc6, 0x1a, 0x6c, 0xb1, 0x57, 0x72, 0xd8, 0xa7, 0xd8, 0x34, 0xac, 0xfa,
	0x1a, 0xce, 0xbd, 0x48, 0x2f, 0x7a, 0xc9, 0xba, 0xac, 0xb1, 0xcb, 0x3d, 0xbe, 0xd7, 0xe6, 0x52,
	0xe1, 0x35, 0x38, 0xfb, 0xa6, 0x25, 0xa2, 0x6d, 0xe6, 0xfb, 0x2d, 0x2e, 0x65, 0x09, 0x55, 0x50,
	0xad, 0xe0, 0x15, 0xd3, 0xda, 0x7d, 0x53, 0xc2, 0xab, 0x00, 0x4a, 0x8c, 0x00, 0xf3, 0x1a, 0x50,
	0x50, 0xc2, 0x1e, 0x57, 0x6f, 0xc1, 0xf9, 0xe9, 0x8b, 0x65, 0x22, 0x62, 0xc9, 0x71, 0x09, 0x16,
	0x95, 0x29, 0xe9, 0x4b, 0x97, 0xbc, 0xec, 0x6f, 0x35, 0x80, 0xd5, 0xac, 0xe3, 0x51, 0xa6, 0x72,
	0x4b, 0xc4, 0x5c, 0x66, 0xa2, 0x1e, 0x03, 0x8c, 0xc7, 0xd4, 0x8c, 0xc5, 0xfa, 0x55, 0x62, 0x3c,
	0x21, 0xa9, 0x27, 0xc4, 0xd8, 0x6b, 0x3d, 0x21, 0xcf, 0x59, 0x90, 0x0d, 0xe4, 0x4d, 0x74, 0x56,
	0xbf, 0x20, 0x70, 0x0e, 0x63, 0xb2, 0x2a, 0x09, 0x2c, 0xbc, 0x4d, 0x0b, 0x25, 0x54, 0x39, 0x55,
	0x2b, 0xd6, 0x4b, 0x64, 0x76, 0x57, 0x24, 0xed, 0xf0, 0x0c, 0x0c, 0x3f, 0xc9, 0x91, 0xb6, 0x7e,
	0xa4, 0x34, 0x43, 0x36, 0xa5, 0xed, 0x03, 0x82, 0xcb, 0x33, 0xda, 0xac, 0xa7, 0x99, 0x0f, 0xcb,
	0x50, 0x48, 0x59, 0xb7, 0x63, 0x16, 0x71, 0xbb, 0x99, 0xa5, 0xb4, 0xf0, 0x8c, 0x45, 0xfc, 0xc4,
	0x4c, 0xfa, 0x88, 0xa0, 0x72, 0xb8, 0x10, 0x6b, 0xd3, 0x0a, 0x14, 0x6c, 0x00, 0xac, 0x55, 0x05,
	0x6f, 0x5c, 0x38, 0x31, 0x53, 0xea, 0xef, 0x4f, 0xc3, 0x82, 0xd6, 0x82, 0xbf, 0x22, 0x58, 0xb4,
	0x89, 0xc2, 0xeb, 0x79, 0x4b, 0xc9, 0x09, 0x73, 0xb9, 0x76, 0x34, 0xd0, 0x90, 0x56, 0xef, 0xbd,
	0xfb, 0xf9, 0xe7, 0xf3, 0xfc, 0x1d, 0x7c, 0x9b, 0xe6, 0xbf, 0x9e, 0x14, 0x4c, 0x7b, 0x93, 0x2f,
	0xa3, 0x4f, 0x7b, 0xe3, 0x57, 0xd0, 0xc7, 0xdf, 0x10, 0x5c, 0x98, 0x49, 0xd5, 0xd3, 0x50, 0x2a,
	0xec, 0xfe, 0x4b, 0x44, 0x6e, 0xde, 0xcb, 0xf5, 0xe3, 0xb4, 0xd8, 0x09, 0xd6, 0xf4, 0x04, 0xcb,
	0xf8, 0x52, 0xde, 0x04, 0x26, 0xab, 0xdf, 0x11, 0x5c, 0xcc, 0x59, 0xaa, 0x56, 0xb9, 0xf1, 0x5f,
	0x94, 0xd3, 0x79, 0x2c, 0x6f, 0x1e, 0xaf, 0xc9, 0x2a, 0x75, 0xb5, 0xd2, 0x1b, 0xf8, 0x5a, 0x9e,
	0xd2, 0xde, 0x28, 0xe0, 0x7d, 0x3a, 0x0a, 0xd4, 0x83, 0x57, 0x3f, 0x06, 0x0e, 0x3a, 0x18, 0x38,
	0xe8, 0xf7, 0xc0, 0x41, 0x9f, 0x86, 0xce, 0xdc, 0xc1, 0xd0, 0x99, 0xfb, 0x35, 0x74, 0xe6, 0xb6,
	0xee, 0x06, 0xa1, 0xda, 0x69, 0x37, 0x48, 0x53, 0x44, 0xf4, 0x21, 0xeb, 0x84, 0xbe, 0x2f, 0x9a,
	0x3b, 0x2c, 0x8c, 0xa9, 0xfd, 0xbd, 0xd9, 0x14, 0x2d, 0x4e, 0x3b, 0x9b, 0xb4, 0x3b, 0x4d, 0xa5,
	0xf6, 0x13, 0x2e, 0x1b, 0x67, 0xf4, 0xb7, 0x70, 0xe3, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xa5,
	0x21, 0x07, 0x4d, 0xb2, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	Taxable(ctx context.Context, in *QueryTaxableRequest, opts ...grpc.CallOption) (*QueryTaxableResponse, error)
	TaxExemptionZonesList(ctx context.Context, in *QueryTaxExemptionZonesRequest, opts ...grpc.CallOption) (*QueryTaxExemptionZonesResponse, error)
	TaxExemptionAddressList(ctx context.Context, in *QueryTaxExemptionAddressRequest, opts ...grpc.CallOption) (*QueryTaxExemptionAddressResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Taxable(ctx context.Context, in *QueryTaxableRequest, opts ...grpc.CallOption) (*QueryTaxableResponse, error) {
	out := new(QueryTaxableResponse)
	err := c.cc.Invoke(ctx, "/do.taxexemption.v1.Query/Taxable", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) TaxExemptionZonesList(ctx context.Context, in *QueryTaxExemptionZonesRequest, opts ...grpc.CallOption) (*QueryTaxExemptionZonesResponse, error) {
	out := new(QueryTaxExemptionZonesResponse)
	err := c.cc.Invoke(ctx, "/do.taxexemption.v1.Query/TaxExemptionZonesList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) TaxExemptionAddressList(ctx context.Context, in *QueryTaxExemptionAddressRequest, opts ...grpc.CallOption) (*QueryTaxExemptionAddressResponse, error) {
	out := new(QueryTaxExemptionAddressResponse)
	err := c.cc.Invoke(ctx, "/do.taxexemption.v1.Query/TaxExemptionAddressList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	Taxable(context.Context, *QueryTaxableRequest) (*QueryTaxableResponse, error)
	TaxExemptionZonesList(context.Context, *QueryTaxExemptionZonesRequest) (*QueryTaxExemptionZonesResponse, error)
	TaxExemptionAddressList(context.Context, *QueryTaxExemptionAddressRequest) (*QueryTaxExemptionAddressResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Taxable(ctx context.Context, req *QueryTaxableRequest) (*QueryTaxableResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Taxable not implemented")
}
func (*UnimplementedQueryServer) TaxExemptionZonesList(ctx context.Context, req *QueryTaxExemptionZonesRequest) (*QueryTaxExemptionZonesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TaxExemptionZonesList not implemented")
}
func (*UnimplementedQueryServer) TaxExemptionAddressList(ctx context.Context, req *QueryTaxExemptionAddressRequest) (*QueryTaxExemptionAddressResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TaxExemptionAddressList not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Taxable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryTaxableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Taxable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/do.taxexemption.v1.Query/Taxable",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Taxable(ctx, req.(*QueryTaxableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_TaxExemptionZonesList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryTaxExemptionZonesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).TaxExemptionZonesList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/do.taxexemption.v1.Query/TaxExemptionZonesList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).TaxExemptionZonesList(ctx, req.(*QueryTaxExemptionZonesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_TaxExemptionAddressList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryTaxExemptionAddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).TaxExemptionAddressList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/do.taxexemption.v1.Query/TaxExemptionAddressList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).TaxExemptionAddressList(ctx, req.(*QueryTaxExemptionAddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "do.taxexemption.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Taxable",
			Handler:    _Query_Taxable_Handler,
		},
		{
			MethodName: "TaxExemptionZonesList",
			Handler:    _Query_TaxExemptionZonesList_Handler,
		},
		{
			MethodName: "TaxExemptionAddressList",
			Handler:    _Query_TaxExemptionAddressList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "do/taxexemption/v1/query.proto",
}

func (m *QueryTaxableRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryTaxableRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryTaxableRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ToAddress) > 0 {
		i -= len(m.ToAddress)
		copy(dAtA[i:], m.ToAddress)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.ToAddress)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.FromAddress) > 0 {
		i -= len(m.FromAddress)
		copy(dAtA[i:], m.FromAddress)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.FromAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryTaxableResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryTaxableResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryTaxableResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Taxable {
		i--
		if m.Taxable {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryTaxExemptionZonesRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryTaxExemptionZonesRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryTaxExemptionZonesRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	return len(dAtA) - i, nil
}

func (m *QueryTaxExemptionZonesResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryTaxExemptionZonesResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryTaxExemptionZonesResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Zones) > 0 {
		for iNdEx := len(m.Zones) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Zones[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryTaxExemptionAddressRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryTaxExemptionAddressRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryTaxExemptionAddressRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.ZoneName) > 0 {
		i -= len(m.ZoneName)
		copy(dAtA[i:], m.ZoneName)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.ZoneName)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryTaxExemptionAddressResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryTaxExemptionAddressResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryTaxExemptionAddressResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Addresses) > 0 {
		for iNdEx := len(m.Addresses) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Addresses[iNdEx])
			copy(dAtA[i:], m.Addresses[iNdEx])
			i = encodeVarintQuery(dAtA, i, uint64(len(m.Addresses[iNdEx])))
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryTaxableRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.FromAddress)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.ToAddress)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryTaxableResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Taxable {
		n += 2
	}
	return n
}

func (m *QueryTaxExemptionZonesRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryTaxExemptionZonesResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Zones) > 0 {
		for _, e := range m.Zones {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryTaxExemptionAddressRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ZoneName)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryTaxExemptionAddressResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Addresses) > 0 {
		for _, s := range m.Addresses {
			l = len(s)
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryTaxableRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryTaxableRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryTaxableRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FromAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FromAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ToAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ToAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryTaxableResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryTaxableResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryTaxableResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Taxable", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Taxable = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryTaxExemptionZonesRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryTaxExemptionZonesRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryTaxExemptionZonesRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryTaxExemptionZonesResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryTaxExemptionZonesResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryTaxExemptionZonesResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Zones", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Zones = append(m.Zones, &Zone{})
			if err := m.Zones[len(m.Zones)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryTaxExemptionAddressRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryTaxExemptionAddressRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryTaxExemptionAddressRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ZoneName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ZoneName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryTaxExemptionAddressResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryTaxExemptionAddressResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryTaxExemptionAddressResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Addresses", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Addresses = append(m.Addresses, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
